server:
  port: 8082

spring:
  application:
    name: resource-service
  boot:
    admin:
      client:
        url: http://localhost:8080
        username: sbadmin
        password: pass
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json

management:
  endpoints:
    web:
      exposure:
        include: "*"