version: '3'

services:
  authorization-server:
    build:
      context: ./spring-boot-admin-sample-oauth2-authorization
    container_name: sba-oauth2-auth
    ports:
      - 8081:8081

  admin-server:
    build:
      context: ./spring-boot-admin-sample-oauth2-admin
    container_name: sba-oauth2-admin
    environment:
      cloudfoundry.uaa.host: authorization-server
      cloudfoundry.uaa.port: 8081
    depends_on:
      - authorization-server
    command: ["./wait-for.sh authorization-server:8081 --timeout=120 -- java -jar app.jar"]
    ports:
      - 8080:8080

  resource-server:
    build:
      context: ./spring-boot-admin-sample-oauth2-resource
    container_name: sba-oauth2-resource
    environment:
      cloudfoundry.uaa.host: authorization-server
      cloudfoundry.uaa.port: 8081
      spring.boot.admin.client.url: http://admin-server:8080
    depends_on:
      - authorization-server
      - admin-server
    command: ["./wait-for.sh admin-server:8080 --timeout=120 -- java -jar app.jar"]
    ports:
      - 8082:8082