server:
  port: 8080

cloudfoundry:
  uaa:
    host: localhost
    port: 8081

spring:
  security:
    user:
      name: sbadmin
      password: pass
    oauth2:
      client:
        registration:
          my-client:
            client-id: admin
            client-secret: secret
            provider: my-provider
            client-authentication-method: basic
            authorization-grant-type: password
        provider:
          my-provider:
            token-uri: http://${cloudfoundry.uaa.host}:${cloudfoundry.uaa.port}/uaa/oauth/token